name: ML Pipeline Automation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  preprocess-train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install pandas scikit-learn joblib google-cloud-bigquery google-cloud-storage flask numpy

      - name: Run Data Preprocessing
        run: python src/data_load.py

      - name: Train Model
        run: python src/train.py --model-output-path model/

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model/

  deploy:
    needs: preprocess-train
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Model to Cloud Run
        run: |
          gcloud auth login --cred-file=${{ secrets.GCP_SA_KEY }}
          gcloud run deploy ml-model --image=gcr.io/your-project/ml-model --platform=managed --region=us-central1
